# Generated by Django 5.2.8 on 2025-11-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lluvia Torrencial, Concierto en Estadio', max_length=100)),
                ('tipo', models.CharField(choices=[('CLIMA', 'Condición Climática'), ('EVENTO', 'Evento Social/Deportivo'), ('OBRA', 'Obra Vial / Construcción'), ('ACCIDENTE', 'Accidente de Tránsito'), ('ESCUELA', 'Horario Escolar')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('nivel_impacto', models.IntegerField(choices=[(1, 'Bajo (Poco tráfico extra)'), (2, 'Medio'), (3, 'Alto (Bastante congestión)'), (4, 'Crítico (Bloqueo total)')], default=2)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Factor Externo',
                'verbose_name_plural': 'Factores Externos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
