"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv # Importar

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# CONFIGURACIÓN GDAL PARA WINDOWS
# --- CONFIGURACIÓN GDAL BLINDADA PARA WINDOWS ---
if os.name == 'nt':
    # Buscar automáticamente el entorno virtual
    def find_osgeo_path():
        # Opción 1: Buscar en el directorio actual y padres
        current_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Buscar en las posibles ubicaciones del entorno virtual
        possible_paths = [
            # Estructura típica: proyecto/backend/env/Lib/site-packages/osgeo
            os.path.join(current_dir, 'env', 'Lib', 'site-packages', 'osgeo'),
            os.path.join(current_dir, '..', 'env', 'Lib', 'site-packages', 'osgeo'),
            os.path.join(current_dir, '..', '..', 'env', 'Lib', 'site-packages', 'osgeo'),
            
            # Estructura alternativa: proyecto/env/Lib/site-packages/osgeo
            os.path.join(current_dir, '..', '..', '..', 'env', 'Lib', 'site-packages', 'osgeo'),
            
            # Para entornos virtuales en otras ubicaciones
            os.path.join(sys.prefix, 'Lib', 'site-packages', 'osgeo')
        ]
        
        for path in possible_paths:
            abs_path = os.path.abspath(path)
            gdal_dll = os.path.join(abs_path, 'gdal.dll')
            if os.path.exists(gdal_dll):
                return abs_path
        
        return None
    
    OSGEO_PATH = find_osgeo_path()
    
    if OSGEO_PATH and OSGEO_PATH not in os.environ['PATH']:
        os.environ['PATH'] = OSGEO_PATH + ';' + os.environ['PATH']
        os.add_dll_directory(OSGEO_PATH)
    
    GDAL_DLL_NAME = 'gdal.dll'
    
    # 4. CRITICO PARA PYTHON 3.8+: Añadir directorio de DLLs de forma segura
    try:
        os.add_dll_directory(OSGEO_PATH)
    except AttributeError:
        pass # En versiones viejas de Python esto no existe, pero tú usas 3.12 así que funcionará

    # 5. Ruta final para Django
    GDAL_LIBRARY_PATH = r"C:\Users\henry\AppData\Local\Programs\OSGeo4W\bin\gdal312.dll"
    GEOS_LIBRARY_PATH = r"C:\Users\henry\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)p1w3!@=)cf9#yz!+mj+res(#gus^t)hk8(s3rhp)s89+j^)1r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # GIS - DEBE IR ANTES DE APP
    'django.contrib.gis',

    # Terceros
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'django_filters',

    # Tu app
    'trafico',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT')
    }
}


print(f'Current database engine is {DATABASES["default"]["NAME"]}')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
MAPBOX_ACCESS_TOKEN = os.getenv("MAPBOX_ACCESS_TOKEN")