# Generated by Django 5.2.8 on 2025-11-25 03:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('segmento_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('geometria', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MedicionTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('velocidad_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_congestion', models.IntegerField()),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafico.segmento')),
            ],
        ),
    ]
