# Generated by Django 5.2.8 on 2025-11-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAlterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('segmento_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_fin', to='trafico.segmento')),
                ('segmento_inicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_inicio', to='trafico.segmento')),
            ],
        ),
        migrations.CreateModel(
            name='RutaAlternaSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden del tramo dentro de la ruta')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='trafico.rutaalterna')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafico.segmento')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'segmento', 'orden')},
            },
        ),
    ]
