# Generated by Django 5.2.8 on 2025-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0002_rutaalterna_rutaalternasegmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='longitud_km',
            field=models.FloatField(blank=True, help_text='Longitud total del tramo en kilómetros', null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='paradas_cercanas',
            field=models.IntegerField(default=0, help_text='Cantidad de paradas cercanas en el tramo'),
        ),
    ]
