# Generated by Django 5.2.8 on 2025-11-29 22:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0003_segmento_longitud_km_segmento_paradas_cercanas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(help_text='ID de la parada en OpenStreetMap', max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre de la parada (si existe en OSM)', max_length=200, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Ubicación de la parada (lon/lat en WGS84)', srid=4326)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('segmento', models.ForeignKey(help_text='Segmento al que pertenece esta parada', on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='trafico.segmento')),
            ],
            options={
                'verbose_name': 'Parada de bus',
                'verbose_name_plural': 'Paradas de bus',
            },
        ),
    ]
