# Generated by Django 5.2.8 on 2025-11-28 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trafico', '0003_segmento_longitud_km_segmento_paradas_cercanas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionRutaOptima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_objetivo', models.DateTimeField(help_text='Fecha y hora para la cual esta ruta es la mejor', unique=True)),
                ('tiempo_promedio_estimado', models.DecimalField(decimal_places=2, help_text='Tiempo total estimado en minutos', max_digits=10)),
                ('nivel_trafico_promedio', models.DecimalField(decimal_places=2, help_text='Promedio de congestión de la ruta completa', max_digits=4)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, help_text='Cuándo se tomó esta decisión')),
                ('ruta_recomendada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='trafico.rutaalterna')),
            ],
            options={
                'verbose_name': 'Predicción de Ruta Óptima',
                'verbose_name_plural': 'Predicciones de Rutas Óptimas',
                'ordering': ['-fecha_hora_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionPorSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_prediccion', models.DateTimeField(help_text='Fecha y hora para la cual se hace la predicción')),
                ('nivel_congestion_predicho', models.IntegerField(help_text='Nivel de congestión estimado (0-2)')),
                ('velocidad_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se generó este registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='trafico.segmento')),
            ],
            options={
                'verbose_name': 'Predicción por Segmento',
                'verbose_name_plural': 'Predicciones por Segmento',
                'ordering': ['fecha_hora_prediccion'],
                'unique_together': {('segmento', 'fecha_hora_prediccion')},
            },
        ),
    ]
